- name: learntest
  schedule_interval: * /10 * * * * # 
  job_name_prefix: learn-test
  table_list:
    - table_name: searches_raw
      s3_key_input: inbound/searches/
      s3_key_output: outbound/searches-out/
    - table_name: visitors_raw
      s3_key_input: inbound/visitors/
      s3_key_output: outbound/visitors-out/
